### ISSUE TITLE
colaboración

### ISSUE THREAD

**Issue by Yonier** [spenafajuri/covid19#5]
Hola,

Te cuento que estoy desarrollando un mapa interactivo para mostrar los casos en Chile a base de la data que subiste a tu repo, te dejo una previa:

https://i.imgur.com/2dI5Bwx.png
https://i.imgur.com/TJpn98r.png

Tengo ya desarrollada un API que recoge la información nueva de tu repo y la guarda en una DB en la nube automáticamente... lo hice con la lógica de que supuestamente seguirías actualizandolo pero no fue así,

Ojalá pudieras colaborarme a mantener actualizada esa información, o ayudarme a sacarla de otra fuente externa para mantener informado el público Chileno!

Gracias, saludos!

**Comment by wachunei** [comment]
Hola @Yonier,

Si bien no es mi repo he estado colaborando y creo que lamentablemente la información en este formato ya no puede ser actualizada debido a que el Ministerio de Salud dejó de publicar los casos de forma desagregada :(

Acá te dejo otra fuente: https://github.com/maibennett/code/tree/master/covid, pero es el mismo problema del recurso del minsal.

**Comment by spenafajuri** [comment]
Hola Yonier,

Con qué datos hiciste las fotos? El Minsal hasta ahora ha dado información detallada por paciente pero sin la comuna de residencia. O lo que marcas es el centro de salud?

Desde el 18 de marzo, el Minsal sólo libera datos agregados a nivel regional. Se puede hacer un mapa y un GIF colapsando los datos por región de los días previos e incluyendo la información nueva.

Si te sirve, puedo seguir agregando los datos agregados a nivel regional, dime qué estructura de los datos te sería más útil si así fuera.

Saludos y gracias,
Sebastián

**Comment by Yonier** [comment]
> Hola Yonier,
> 
> Con qué datos hiciste las fotos? El Minsal hasta ahora ha dado información detallada por paciente pero sin la comuna de residencia. O lo que marcas es el centro de salud?
> 
> Desde el 18 de marzo, el Minsal sólo libera datos agregados a nivel regional. Se puede hacer un mapa y un GIF colapsando los datos por región de los días previos e incluyendo la información nueva.
> 
> Si te sirve, puedo seguir agregando los datos agregados a nivel regional, dime qué estructura de los datos te sería más útil si así fuera.
> 
> Saludos y gracias,
> Sebastián

Hola @spenafajuri,

Esos datos que salen en las fotos son a base de la localización del hospital en la comuna... qué lástima que el Minsal dejó de subir esa información! :( 

Muchas gracias de todas formas, cuando el mapa este terminado les comparto el link para que lo vean si quieren

**Comment by spenafajuri** [comment]
Compañeros, estamos buscando desarrolladores para un proyecto colectivo de COVID-19. Tiene que ver con sistematizar y visualizar las políticas públicas tomadas a la fecha.

Si quieren unirse, escríbanme a sebastian.penafajuri@thl.fi para más detalles.

**Comment by javierconcha** [comment]
Estimados,
He creado el siguiente [mapa interactivo](http://www.sci-solve.com/covid-19-Chile/index.html) para visualizar la serie temporal de casos en Chile por regiones, con el source code y datos en el siguiente [repo](https://github.com/javierconcha/covid-19-Chile).

Veo que existe un problema en comun que todos estamos enfrentando: Los datos en detalle no se estan entregando en un formato standard y de manera sistematica desde las autoridades. Para mi caso en particular, me gustaria saber el detalles de los recuperados por regiones.

Quizas podamos juntar fuerzas para sugerir al minsal de entregar mas detalles? Alguna sugerenccia? Comentario?
Saludos,
Javier
